name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test_smart_contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - name: "Install SmartPy"
      run: |
        curl -s https://smartpy.io/releases/20210326-d2f24290eef00fe8cc3d482f052165a71a635fa3/cli/install.sh | sh -s -- local-install ~/smartpy-cli
    - name: "Build and Test Smart Contracts"
      run: |
        cd smart_contracts
        ./compile.sh
  lint_and_build_deploy_scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: "Install Dependencies"
      run: |
        sudo apt-get update && sudo apt-get install build-essential git libusb-1.0-0 libusb-1.0-0-dev libudev-dev
    - name: "Build and lint deploy scripts"
      run: |
        cd deploy
        npm i
        npm run lint
        npm run build
